debug: true
server:
  port: 8080
  name: example
  cache_html: false
context:
  timeout: 60
id_generator:
  distributed: false
database:
  use: true
  host: localhost
  port: 5432
  user: postgres
  pass: admin@123
  name: example
nats_queue:
  use: true
  url: localhost:4222
redis:
  use: false
  host: localhost
  port: 12345
proxy:
  url:
http_client:
  retry_times:
  wait_times:
scheduler:
  use: false
  task_doing_expiration: 60
  delay: 2
  interval:
  bucket_size: 20
  task_timeout: 60
