// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: http_model.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []string               `protobuf:"bytes,2,rep,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_http_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_http_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_http_model_proto_rawDescGZIP(), []int{0}
}

func (x *Header) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Header) GetValue() []string {
	if x != nil {
		return x.Value
	}
	return nil
}

type QueryParam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []string               `protobuf:"bytes,2,rep,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryParam) Reset() {
	*x = QueryParam{}
	mi := &file_http_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParam) ProtoMessage() {}

func (x *QueryParam) ProtoReflect() protoreflect.Message {
	mi := &file_http_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParam.ProtoReflect.Descriptor instead.
func (*QueryParam) Descriptor() ([]byte, []int) {
	return file_http_model_proto_rawDescGZIP(), []int{1}
}

func (x *QueryParam) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *QueryParam) GetValue() []string {
	if x != nil {
		return x.Value
	}
	return nil
}

type FormData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []string               `protobuf:"bytes,2,rep,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FormData) Reset() {
	*x = FormData{}
	mi := &file_http_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FormData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormData) ProtoMessage() {}

func (x *FormData) ProtoReflect() protoreflect.Message {
	mi := &file_http_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormData.ProtoReflect.Descriptor instead.
func (*FormData) Descriptor() ([]byte, []int) {
	return file_http_model_proto_rawDescGZIP(), []int{2}
}

func (x *FormData) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *FormData) GetValue() []string {
	if x != nil {
		return x.Value
	}
	return nil
}

type Cookie struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Quoted        bool                   `protobuf:"varint,3,opt,name=quoted,proto3" json:"quoted,omitempty"`                          // indicates whether the Value was originally quoted
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`                               // optional
	Domain        string                 `protobuf:"bytes,5,opt,name=domain,proto3" json:"domain,omitempty"`                           // optional
	Expires       int64                  `protobuf:"varint,6,opt,name=expires,proto3" json:"expires,omitempty"`                        // Unix timestamp (time.Time)
	RawExpires    string                 `protobuf:"bytes,7,opt,name=raw_expires,json=rawExpires,proto3" json:"raw_expires,omitempty"` // for reading cookies only
	MaxAge        int32                  `protobuf:"varint,8,opt,name=max_age,json=maxAge,proto3" json:"max_age,omitempty"`            // MaxAge=0 means no 'Max-Age' attribute specified
	Secure        bool                   `protobuf:"varint,9,opt,name=secure,proto3" json:"secure,omitempty"`
	HttpOnly      bool                   `protobuf:"varint,10,opt,name=http_only,json=httpOnly,proto3" json:"http_only,omitempty"`
	SameSite      int32                  `protobuf:"varint,11,opt,name=same_site,json=sameSite,proto3" json:"same_site,omitempty"` // SameSite enum as string
	Partitioned   bool                   `protobuf:"varint,12,opt,name=partitioned,proto3" json:"partitioned,omitempty"`
	Raw           string                 `protobuf:"bytes,13,opt,name=raw,proto3" json:"raw,omitempty"`           // Raw cookie string
	Unparsed      []string               `protobuf:"bytes,14,rep,name=unparsed,proto3" json:"unparsed,omitempty"` // Raw text of unparsed attribute-value pairs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cookie) Reset() {
	*x = Cookie{}
	mi := &file_http_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cookie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cookie) ProtoMessage() {}

func (x *Cookie) ProtoReflect() protoreflect.Message {
	mi := &file_http_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cookie.ProtoReflect.Descriptor instead.
func (*Cookie) Descriptor() ([]byte, []int) {
	return file_http_model_proto_rawDescGZIP(), []int{3}
}

func (x *Cookie) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Cookie) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Cookie) GetQuoted() bool {
	if x != nil {
		return x.Quoted
	}
	return false
}

func (x *Cookie) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Cookie) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Cookie) GetExpires() int64 {
	if x != nil {
		return x.Expires
	}
	return 0
}

func (x *Cookie) GetRawExpires() string {
	if x != nil {
		return x.RawExpires
	}
	return ""
}

func (x *Cookie) GetMaxAge() int32 {
	if x != nil {
		return x.MaxAge
	}
	return 0
}

func (x *Cookie) GetSecure() bool {
	if x != nil {
		return x.Secure
	}
	return false
}

func (x *Cookie) GetHttpOnly() bool {
	if x != nil {
		return x.HttpOnly
	}
	return false
}

func (x *Cookie) GetSameSite() int32 {
	if x != nil {
		return x.SameSite
	}
	return 0
}

func (x *Cookie) GetPartitioned() bool {
	if x != nil {
		return x.Partitioned
	}
	return false
}

func (x *Cookie) GetRaw() string {
	if x != nil {
		return x.Raw
	}
	return ""
}

func (x *Cookie) GetUnparsed() []string {
	if x != nil {
		return x.Unparsed
	}
	return nil
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Headers       map[string]*Header     `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	QueryParams   map[string]*QueryParam `protobuf:"bytes,5,rep,name=queryParams,proto3" json:"queryParams,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	UrlParams     map[string]string      `protobuf:"bytes,6,rep,name=urlParams,proto3" json:"urlParams,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ContextId     string                 `protobuf:"bytes,7,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	Data          map[string]string      `protobuf:"bytes,8,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Cookies       map[string]*Cookie     `protobuf:"bytes,9,rep,name=cookies,proto3" json:"cookies,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	FormData      map[string]*FormData   `protobuf:"bytes,10,rep,name=formData,proto3" json:"formData,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_http_model_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_http_model_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_http_model_proto_rawDescGZIP(), []int{4}
}

func (x *Request) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Request) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Request) GetHeaders() map[string]*Header {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Request) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Request) GetQueryParams() map[string]*QueryParam {
	if x != nil {
		return x.QueryParams
	}
	return nil
}

func (x *Request) GetUrlParams() map[string]string {
	if x != nil {
		return x.UrlParams
	}
	return nil
}

func (x *Request) GetContextId() string {
	if x != nil {
		return x.ContextId
	}
	return ""
}

func (x *Request) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Request) GetCookies() map[string]*Cookie {
	if x != nil {
		return x.Cookies
	}
	return nil
}

func (x *Request) GetFormData() map[string]*FormData {
	if x != nil {
		return x.FormData
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Headers       map[string]*Header     `protobuf:"bytes,1,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ResponseBody  []byte                 `protobuf:"bytes,2,opt,name=response_body,json=responseBody,proto3" json:"response_body,omitempty"`
	StatusCode    int32                  `protobuf:"varint,3,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	RedirectLink  string                 `protobuf:"bytes,4,opt,name=redirect_link,json=redirectLink,proto3" json:"redirect_link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_http_model_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_http_model_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_http_model_proto_rawDescGZIP(), []int{5}
}

func (x *Response) GetHeaders() map[string]*Header {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Response) GetResponseBody() []byte {
	if x != nil {
		return x.ResponseBody
	}
	return nil
}

func (x *Response) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *Response) GetRedirectLink() string {
	if x != nil {
		return x.RedirectLink
	}
	return ""
}

var File_http_model_proto protoreflect.FileDescriptor

const file_http_model_proto_rawDesc = "" +
	"\n" +
	"\x10http_model.proto\x12\x04core\"0\n" +
	"\x06Header\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x03(\tR\x05value\"4\n" +
	"\n" +
	"QueryParam\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x03(\tR\x05value\"2\n" +
	"\bFormData\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x03(\tR\x05value\"\xec\x02\n" +
	"\x06Cookie\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x16\n" +
	"\x06quoted\x18\x03 \x01(\bR\x06quoted\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x16\n" +
	"\x06domain\x18\x05 \x01(\tR\x06domain\x12\x18\n" +
	"\aexpires\x18\x06 \x01(\x03R\aexpires\x12\x1f\n" +
	"\vraw_expires\x18\a \x01(\tR\n" +
	"rawExpires\x12\x17\n" +
	"\amax_age\x18\b \x01(\x05R\x06maxAge\x12\x16\n" +
	"\x06secure\x18\t \x01(\bR\x06secure\x12\x1b\n" +
	"\thttp_only\x18\n" +
	" \x01(\bR\bhttpOnly\x12\x1b\n" +
	"\tsame_site\x18\v \x01(\x05R\bsameSite\x12 \n" +
	"\vpartitioned\x18\f \x01(\bR\vpartitioned\x12\x10\n" +
	"\x03raw\x18\r \x01(\tR\x03raw\x12\x1a\n" +
	"\bunparsed\x18\x0e \x03(\tR\bunparsed\"\xe0\x06\n" +
	"\aRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x124\n" +
	"\aheaders\x18\x03 \x03(\v2\x1a.core.Request.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\x12@\n" +
	"\vqueryParams\x18\x05 \x03(\v2\x1e.core.Request.QueryParamsEntryR\vqueryParams\x12:\n" +
	"\turlParams\x18\x06 \x03(\v2\x1c.core.Request.UrlParamsEntryR\turlParams\x12\x1d\n" +
	"\n" +
	"context_id\x18\a \x01(\tR\tcontextId\x12+\n" +
	"\x04data\x18\b \x03(\v2\x17.core.Request.DataEntryR\x04data\x124\n" +
	"\acookies\x18\t \x03(\v2\x1a.core.Request.CookiesEntryR\acookies\x127\n" +
	"\bformData\x18\n" +
	" \x03(\v2\x1b.core.Request.FormDataEntryR\bformData\x1aH\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\"\n" +
	"\x05value\x18\x02 \x01(\v2\f.core.HeaderR\x05value:\x028\x01\x1aP\n" +
	"\x10QueryParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.core.QueryParamR\x05value:\x028\x01\x1a<\n" +
	"\x0eUrlParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aH\n" +
	"\fCookiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\"\n" +
	"\x05value\x18\x02 \x01(\v2\f.core.CookieR\x05value:\x028\x01\x1aK\n" +
	"\rFormDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12$\n" +
	"\x05value\x18\x02 \x01(\v2\x0e.core.FormDataR\x05value:\x028\x01\"\xf6\x01\n" +
	"\bResponse\x125\n" +
	"\aheaders\x18\x01 \x03(\v2\x1b.core.Response.HeadersEntryR\aheaders\x12#\n" +
	"\rresponse_body\x18\x02 \x01(\fR\fresponseBody\x12\x1f\n" +
	"\vstatus_code\x18\x03 \x01(\x05R\n" +
	"statusCode\x12#\n" +
	"\rredirect_link\x18\x04 \x01(\tR\fredirectLink\x1aH\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\"\n" +
	"\x05value\x18\x02 \x01(\v2\f.core.HeaderR\x05value:\x028\x01B!Z\x1fgithub.com/dangviethung096/coreb\x06proto3"

var (
	file_http_model_proto_rawDescOnce sync.Once
	file_http_model_proto_rawDescData []byte
)

func file_http_model_proto_rawDescGZIP() []byte {
	file_http_model_proto_rawDescOnce.Do(func() {
		file_http_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_http_model_proto_rawDesc), len(file_http_model_proto_rawDesc)))
	})
	return file_http_model_proto_rawDescData
}

var file_http_model_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_http_model_proto_goTypes = []any{
	(*Header)(nil),     // 0: core.Header
	(*QueryParam)(nil), // 1: core.QueryParam
	(*FormData)(nil),   // 2: core.FormData
	(*Cookie)(nil),     // 3: core.Cookie
	(*Request)(nil),    // 4: core.Request
	(*Response)(nil),   // 5: core.Response
	nil,                // 6: core.Request.HeadersEntry
	nil,                // 7: core.Request.QueryParamsEntry
	nil,                // 8: core.Request.UrlParamsEntry
	nil,                // 9: core.Request.DataEntry
	nil,                // 10: core.Request.CookiesEntry
	nil,                // 11: core.Request.FormDataEntry
	nil,                // 12: core.Response.HeadersEntry
}
var file_http_model_proto_depIdxs = []int32{
	6,  // 0: core.Request.headers:type_name -> core.Request.HeadersEntry
	7,  // 1: core.Request.queryParams:type_name -> core.Request.QueryParamsEntry
	8,  // 2: core.Request.urlParams:type_name -> core.Request.UrlParamsEntry
	9,  // 3: core.Request.data:type_name -> core.Request.DataEntry
	10, // 4: core.Request.cookies:type_name -> core.Request.CookiesEntry
	11, // 5: core.Request.formData:type_name -> core.Request.FormDataEntry
	12, // 6: core.Response.headers:type_name -> core.Response.HeadersEntry
	0,  // 7: core.Request.HeadersEntry.value:type_name -> core.Header
	1,  // 8: core.Request.QueryParamsEntry.value:type_name -> core.QueryParam
	3,  // 9: core.Request.CookiesEntry.value:type_name -> core.Cookie
	2,  // 10: core.Request.FormDataEntry.value:type_name -> core.FormData
	0,  // 11: core.Response.HeadersEntry.value:type_name -> core.Header
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_http_model_proto_init() }
func file_http_model_proto_init() {
	if File_http_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_http_model_proto_rawDesc), len(file_http_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_http_model_proto_goTypes,
		DependencyIndexes: file_http_model_proto_depIdxs,
		MessageInfos:      file_http_model_proto_msgTypes,
	}.Build()
	File_http_model_proto = out.File
	file_http_model_proto_goTypes = nil
	file_http_model_proto_depIdxs = nil
}
